name: Deploy Docs to Pages

on:
  push:
    branches: ["main"] # Or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Adjust to your pnpm version

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      # Fix: GitHub Pages needs an index.html at the root of 'dist'
      # This redirects carats.dev -> carats.dev/en/latest/
      # - name: Create Redirect Root
      #   run: |
      #     echo '<meta http-equiv="refresh" content="0; url=./en/latest/">' > dist/index.html

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/client'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4